@startuml interactions
SW -> Chrome.scripting: execute content.bundle.js (start react app)
SW -> Chrome.tabs: get tabs
Chrome.tabs --> SW: tabs

SW -> Chrome.scripting: [for active tab] execute dialog.bundle.js

SW -> Parser: [for all tabs] execute
Parser -> SW: sendMessage context = Investing | SeekingAlpha | ...

SW -> MessageBroker: message.context, message.type

@enduml
